import mongoose, { Document, Schema } from 'mongoose';

export interface ICustomComponent extends Document {
    institutionId: mongoose.Types.ObjectId;
    name: string;
    description: string;
    type: string; // The craft.js component name
    props: any;
    jsxCode: string; // The raw JSX code generated by AI (for reference/future editing)
    createdBy: mongoose.Types.ObjectId;
    createdAt: Date;
    updatedAt: Date;
}

const CustomComponentSchema = new Schema<ICustomComponent>(
    {
        institutionId: {
            type: Schema.Types.ObjectId,
            ref: 'Institution',
            required: true,
        },
        name: {
            type: String,
            required: true,
            trim: true,
        },
        description: {
            type: String,
            trim: true,
        },
        type: {
            type: String,
            required: true,
            trim: true,
        },
        props: {
            type: Schema.Types.Mixed,
            default: {},
        },
        jsxCode: {
            type: String,
            required: true,
        },
        createdBy: {
            type: Schema.Types.ObjectId,
            ref: 'User',
            required: true,
        },
    },
    {
        timestamps: true,
    }
);

// Index for fetching per institution
CustomComponentSchema.index({ institutionId: 1, type: 1 });

export const CustomComponent = mongoose.model<ICustomComponent>('CustomComponent', CustomComponentSchema);
